// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxkyacytbqzhagolavbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4a3lhY3l0YnF6aGFnb2xhdmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3NDM4NDQsImV4cCI6MjA1MTMxOTg0NH0.JPoL28HCbVXI_0lhXNsF8fRdWAzHNjwJ7KYU0Mkl78Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);